version: 2.1 #I copied this from https://github.com/kundajelab/basepairmodels/blob/941d354f4526f7dd86c51fed0e22ef5b7dd75c38/.circleci/config.yml

jobs:
  build-and-test:
    docker: # run the steps with Docker
      - image: circleci/python:3.8
    steps:
      - checkout
      #Install miniconda and create the testing environment
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - run: bash miniconda.sh -b -p $HOME/miniconda
      #writing to $BASH_ENV is apparently the way to preserv an environment var between steps
      - run: echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $BASH_ENV
      - run: echo $PATH
      - run: ls $HOME/miniconda/bin
      - run: hash -r
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      - run: conda info -a
      - run: conda create -q -n test-environment python=3.8 numpy pytest h5py nose
      - run:
          command: |
            source activate test-environment
            which pytest
      - run:
          command: |
            source activate test-environment
            pip install tensorflow==2.3.0
            pip install joblib
            pip install scikit-learn
            pip install leidenalg
            pip install tqdm
            pip install psutil
            pip install matplotlib
      - run: echo $PWD
      - run: echo $PYTHONPATH
      #Actually run the tests
      - run: source activate test-environment | PYTHONPATH=$PWD:$PYTHONPATH pytest 
      #MEME installation
      - run: sudo apt-get install -y ghostscript-x
      - run: mkdir -p ~/.config/matplotlib/
      - run: "echo backend : Agg >  ~/.config/matplotlib/matplotlibrc"
      - run: cat ~/.config/matplotlib/matplotlibrc
      - run: which gs
      - run: echo 'export PERL5LIB="$HOME/perl5/lib/perl5:$PERL5LIB"' >> $BASH_ENV
      - run: curl -L http://cpanmin.us | perl - File::Which
      - run: curl -L http://cpanmin.us | perl - HTML::PullParser
      - run: curl -L http://cpanmin.us | perl - HTML::Template
      - run: curl -L http://cpanmin.us | perl - HTML::TreeBuilder
      - run: curl -L http://cpanmin.us | perl - JSON
      - run: curl -L http://cpanmin.us | perl - XML::Simple
      - run: curl -L http://cpanmin.us | perl - XML::Parser::Expat
      - run: wget http://meme-suite.org/meme-software/5.1.1/meme-5.1.1.tar.gz
      - run: tar zxf meme-5.1.1.tar.gz
      - run: cd meme-5.1.1 | perl scripts/dependencies.pl
      - run: cd meme-5.1.1 | ./configure --prefix=$HOME/meme --with-url=http://alternate.meme-suite.org/  --enable-serial --enable-build-libxml2 --enable-build-libxslt
      - run: cd meme-5.1.1 | make
      #- make test; skip the tests since some of them are buggy and stall the build
      # (see: https://groups.google.com/forum/#!topic/meme-suite/D3XR7Ws1gec)
      - run: cd meme-5.1.1 | make install
      - run: echo 'export PATH="$HOME/meme/bin:$PATH"' >> $BASH_ENV
      - run: echo $PWD
      - run: echo $PYTHONPATH
      #Actually run the tests
      - run: PYTHONPATH=$PWD:$PYTHONPATH py.test           
#      - restore_cache:
#      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#      - run:
#          command: |
#            sudo pip install pipenv
#            pipenv install
#      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#          paths:
#            - "venv"
#            - "/usr/local/bin"
#            - "/usr/local/lib/python3.7/site-packages"
#      - run:
#          command: |
#            pipenv run python -m pytest
#          name: Test

workflows:
  main:
    jobs:
      - build-and-test
